#!/usr/bin/env python3
import sys
import os
from os import path
import argparse
from argparse import RawTextHelpFormatter

from mpu.command import CmdInfo, Command, CommandManager

from mpu.cmds.init import InitCommand
from mpu.cmds.pkg import PkgCommand
from mpu.cmds.info import InfoCommand
from mpu.cmds.rm import RemoveCommand

def disp_help():
  description = ("""
usage:
  vem <command> [...options]

Available commands:
""")

  for cmd in command_list.cmds:
    description += "  " + (cmd.info.title_help()) + "\n"
  
  return description


command_list = CommandManager([
  Command(CmdInfo("help", "display help")),
  InitCommand(),
  InfoCommand(),
  RemoveCommand(),
  PkgCommand(),
  Command(CmdInfo("config", "udpate or read config to or from VM instance"))
])

def main():
  global command_list

  args = sys.argv

  if(len(args) < 2):
    print(disp_help())
    exit(0)

  func_name = args[1]

  if(command_list.indexOf(func_name) == -1):
    print(f"command \"{func_name}\" not found")
    print(disp_help())
    exit(1)
  
  command_list.exec(func_name)

if __name__ == "__main__":
  main()
else:
  print("Do not run this program without main")
  exit(1)