#!/usr/bin/env python3
import sys
import os
from os import path
# import argparse
# from argparse import RawTextHelpFormatter

from mpu.command import CmdInfo, Command, CommandManager

from mpu.cmds.init import InitCommand
from mpu.cmds.pkg import PkgCommand
from mpu.cmds.info import InfoCommand
from mpu.cmds.rm import RemoveCommand
from mpu.cmds.exec import ExecCommand
from mpu.cmds.doctor.doctor import DoctorCommand

from mpu.controllers.args_controller import ArgsController

command_list = CommandManager([
  Command(CmdInfo("help", "display help")),
  InitCommand(),
  InfoCommand(),
  RemoveCommand(),
  PkgCommand(),
  Command(CmdInfo("config", "udpate or read config to or from VM instance")),
  ExecCommand(),
  DoctorCommand()
])

def main():
  global command_list

  ac = ArgsController()

  if(not ac.isValidCmd()):
    print(disp_help())
    exit(0)

  if(not command_list.run(ac)):
    print(command_list.disp_help())
    exit(1)

if __name__ == "__main__":
  main()
else:
  print("Do not run this program without main")
  exit(1)