#!/usr/bin/env python3
import sys
import os
from os import path
# import argparse
# from argparse import RawTextHelpFormatter

from mpu.command import CmdInfo, Command, CommandManager

from mpu.cmds.init import InitCommand
from mpu.cmds.pkg import PkgCommand
from mpu.cmds.info import InfoCommand
from mpu.cmds.rm import RemoveCommand
from mpu.cmds.exec import ExecCommand, RunCommand
from mpu.cmds.doctor.doctor import DoctorCommand
from mpu.cmds.help import HelpCommand

from mpu.controllers.args_controller import ArgsController
from mpu.controllers.instance_controller import InstanceController
from mpu.mp_controller import MPController

# TODO: read config file and return different InstanceController for different platform
def getInstanceController():
  return MPController()
ic:InstanceController = getInstanceController()

command_list = CommandManager([
  Command(CmdInfo("help", "display help")),
  InitCommand(ic),
  InfoCommand(ic),
  RemoveCommand(ic),
  PkgCommand(ic),
  Command(CmdInfo("config", "udpate or read config to or from VM instance")),
  ExecCommand(ic),
  RunCommand(ic),
  DoctorCommand()
])

command_list.cmds[0] = HelpCommand(command_list)

def main():
  global command_list

  ac = ArgsController()

  if(not ac.isValidCmd()):
    print(command_list.disp_help())
    exit(0)

  if(not command_list.run(ac)):
    print(command_list.disp_help())
    exit(1)

if __name__ == "__main__":
  main()
else:
  print("Do not run this program without main")
  exit(1)